---
title: "Statistical Rethinking Chapter 15"
output: html_notebook
---
```{r results='hide'}
library(rethinking)
data(WaffleDivorce)
d <- WaffleDivorce
dlist <- list(
  D_obs = standardize(d$Divorce),
  D_sd = d$Divorce.SE / sd(d$Divorce),
  M = standardize(d$Marriage),
  A = standardize(d$MedianAgeMarriage),
  N = nrow(d)
)

m15.1 <- ulam(
  alist(
    D_obs ~ dnorm(D_true, D_sd),
    vector[N]:D_true ~dnorm( mu, sigma),
    mu <- a + bA*A + bM*M,
    a ~ dnorm(0, 0.2),
    bA ~ dnorm(0, 0.5),
    bM ~ dnorm(0, 0.5),
    sigma ~ dexp(1)
    ), data=dlist, chains=4, cores=4
)
```
```{r}
precis(m15.1)
```
```{r results='hide'}
m5.3 <- ulam(
alist(
D_obs ~ dnorm( mu , sigma ) ,
mu <- a + bM*M + bA*A ,
a ~ dnorm( 0 , 0.2 ) ,
bA ~ dnorm( 0 , 0.5 ) ,
bM ~ dnorm( 0 , 0.5 ) ,

sigma ~ dexp( 1 )
) , data = dlist, chains=4, cores=4)
```
```{r}
precis( m5.3 )
```
```{r results="hide"}
dlist <- list(
  D_obs = standardize(d$Divorce),
  D_sd = d$Divorce.SE / sd(d$Divorce),
  M_obs = standardize(d$Marriage),
  M_sd = d$Marriage.SE / sd(d$Marriage),
  A = standardize(d$MedianAgeMarriage),
  N = nrow(d)
)
m15.2 <- ulam(
  alist(
    D_obs ~ dnorm(D_true, D_sd),
    vector[N]:D_true ~ dnorm(mu, sigma),
    mu <- a + bA*A + bM*M_true[i],
    M_obs ~ dnorm(M_true, M_sd),
    vector[N]:M_true ~ dnorm(0, 1),
    a ~ dnorm(0, 0.2),
    bA ~ dnorm(0, 0.5),
    bM ~ dnorm(0, 0.5),
    sigma ~ dexp(1)
  ), data=dlist, chains=4, cores=4
)
```
```{r}
precis(m15.2)
```
```{r}
post <- extract.samples( m15.2 )
D_true <- apply( post$D_true , 2 , mean )
M_true <- apply( post$M_true , 2 , mean )
plot( dlist$M_obs , dlist$D_obs , pch=16 , col=rangi2 ,
xlab="marriage rate (std)" , ylab="divorce rate (std)" )
points( M_true , D_true )
for ( i in 1:nrow(d) )
lines( c( dlist$M_obs[i] , M_true[i] ) , c( dlist$D_obs[i] , D_true[i] ) )
```
```{r results="hide"}
data <- list(
N = 500,
A = rnorm(N),
M = rnorm(N, -A),
D = rnorm(N, A),
A_obs = rnorm(N, A)
)


m15.2b <- ulam(
  alist(
    D ~ dnorm(mu, sigma),
    mu <- a + bA*A_obs + bM*M,
    a ~ dnorm(0, 0.2),
    bA ~ dnorm(0, 0.5),
    bM ~ dnorm(0, 0.5),
    sigma ~ dexp(1)
  ), data=data, chains=4, cores=4
)
```
```{r}
precis(m15.2b)
```
```{r}
coeftab_plot(coeftab(m5.3, m15.1, m15.2, m15.2b), pars=c("a", "bA", "bM"))
```